apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java-app
  template:
    metadata:
      labels:
        app: hello-java-app
    spec:
      containers:
      - name: hello-java-app
        image: nipurjain/java-cicd-pipeline:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-java-service
spec:
  selector:
    app: hello-java-app
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
